version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx-proxy:
    user: root
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    environment:
      DEFAULT_HOST: pihole.home.lan
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - ./nginx:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_prox
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/Bogota
    ports:
      - '8123:8123/tcp'
    depends_on:
      - nginx-proxy
  cert-manager:
    user: root
    container_name: cert
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: juanfbbl9307@gmail.com
  pihole:
    container_name: pihole
    pull_policy: always
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
    environment:
      ServerIP: 192.168.1.90
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.home.lan
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: pihole.home.lan
      TZ: 'America/Bogota'
      WEBPASSWORD: "piholelocal"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      - 'home.lan:192.168.1.90'
      - 'pihole pihole.home.lan:192.168.1.90'
      - 'ghost ghost.home.lan:192.168.1.90'
      - 'wordpress wordpress.home.lan:192.168.1.90'
    restart: always
volumes:
  confd:
  vhostd:
  html:
  certs:
  acme:
  portainer_data:
  home_assistant_data:
